--- 
st_password: whoami23
st_user: mcoates@zepinvest.com
st_api_key: eacb7258085b816a1ea0fadcade69e

about_msg: 'Lurch is a time-keeping bot developed by Mark Coates and Noah Sussman at ZepFrog Corp, Copyright 2009. (An Autumn Leaf) http://zepfrog.com/development'
